# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

pool:
  name: $(agentPool)

variables:
  agentPool: 'TestAgent'

stages:
- stage: Validate Entry Criteria
  jobs:
  - job: Do
    steps:
    - script: echo Validate Entry Criteria
      displayName: Run a one-line script
- stage: Execute Build
  jobs:
  - job: Do
    steps:
    - script: echo Execute Build
      displayName: Run a one-line script
- stage: Perform Unit Tests
  jobs:
  - job: Do
    steps:
    - script: echo Perform Unit Tests
      displayName: Run a one-line script
- stage: Analyze Code
  jobs:
  - job: Do
    steps:
    - script: echo Analyze Code
      displayName: Run a one-line script
- stage: Package Artifact
  jobs:
  - job: Do
    steps:
    - script: echo Package Artifact
      displayName: Run a one-line script
- stage: Publish Artifact
  jobs:
  - job: Do
    steps:
    - script: echo Publish Artifact
      displayName: Run a one-line script
- stage: Provision Test Environment
  jobs:
  - job: Do
    steps:
    - script: echo Provision Test Environment
      displayName: Run a one-line script
- stage: Deploy Artifact To Test
  jobs:
  - job: Do
    steps:
    - script: echo Deploy Artifact To Test
      displayName: Run a one-line script
- stage: Perform Test
  jobs:
  - job: Do
    steps:
    - script: echo Perform Test
      displayName: Run a one-line script
- stage: Validate Infrastructure Compliance
  jobs:
  - job: Do
    steps:
    - script: echo Validate Infrastructure Compliance
      displayName: Run a one-line script
- stage: Validate Exit Criteria
  jobs:
  - job: Do
    steps:
    - script: echo Validate Exit Criteria
      displayName: Run a one-line script
- stage: Perform Dual Control
  jobs:
  - job: Do
    steps:
    - script: echo Perform Dual Control
      displayName: Run a one-line script
- stage: Provision Production Environment
  jobs:
  - job: Do
    steps:
    - script: echo Provision Production Environment
      displayName: Run a one-line script
- stage: Deploy Artifact to Production
  jobs:
  - job: Do
    steps:
    - script: echo Deploy Artifact to Production
      displayName: Run a one-line script
- stage: Notify Actors
  jobs:
  - job: Do
    steps:
    - script: echo Notify Actors
      displayName: Run a one-line script

# steps:
# - script: echo Hello, world!
#   displayName: Run a one-line script

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: Run a multi-line script
