trigger:
  - feature-1

pool:
  name: 'TestAgent'

resources:
  repositories:
    - repository: template
      endpoint: quangpham1019 (1)
      type: github
      name: quangpham1019/pipeline-repo

steps:
- template: feature-1-ci-template.yml@template
