trigger:
  - feature-1

pool:
  name: 'TestAgent'

resources:
  repositories:
    - repository: templates
      endpoint: quangpham1019 (1)
      type: github
      name: quangpham1019/pipeline-repo

steps:
  - template: template2.yml
#  parameters:
#    ciSteps:
#      - script: echo Running feature-2-pipeline-ci buildSteps
#      - script: echo Finishing feature-2-pipeline-ci buildSteps