trigger:
  - feature-1

extends:
  template: azure-pipelines.yml
  parameters:
    buildSteps:
      - script: echo Running feature-1-pipeline-ci buildSteps in main
      - script: echo Finishing feature-1-pipeline-ci buildSteps in main